export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";

export const UPLOAD_START = "UPLOAD_START"
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS"
export const UPLOAD_FAIL = "UPLOAD_FAIL"

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';